### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by karendiand** [zjunlp/Relphormer#15]
Global seed set to 7
bert.embeddings.word_embeddings.weight
/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:478: LightningDeprecationWarning: Setting `Trainer(gpus=6)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=6)` instead.
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "main.py", line 128, in <module>
    main()
  File "main.py", line 122, in main
    trainer.fit(lit_model, datamodule=data)
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 113, in launch
    mp.start_processes(
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/media/data2/chenyujie/Anaconda3/envs/kyh/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: 'NoneType' object is not callable
不好意思，请问我这个问题是因为什么引起的

**Comment by bizhen46766** [comment]
您好！请问您对应库的版本是和requirements.txt对应的吗？
